const _conf = require('./webpackConsts').configs;
const path = require('path');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = (env, argv) => {

    let pathsToClean = [
        'dist',
        'build'
    ];

    return {
        devtool: "inline-cheap-module-source-map",
        context: path.resolve(__dirname),
        entry: [
            '@babel/polyfill',
            `webpack-dev-server/client?http://${_conf.server.host}:${_conf.server.port}`,
            _conf.frontEntryPoint.js,
        ],
        output: {
            path: _conf.path.resolve(__dirname, 'dist'),
            filename: '[name].[hash].js'
        },
        devServer: {
            stats: 'normal',
            host: _conf.server.host,
            port: _conf.server.port,
            historyApiFallback: true,
            contentBase: __dirname,
            hot: true,
            headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, GET, PUT, DELETE, OPTIONS"
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                        loader: "babel-loader"
                    }
                },
                {
                    test: /\.(sc|c)ss$/,
                    use: [
                        'style-loader',
                        'css-loader',
                        'postcss-loader',
                        'sass-loader',
                    ],
                },
                {
                    test: /\.(jpg|jpeg|gif|png)$/i,
                    exclude: /node_modules/,
                    loader: 'url-loader'
                },
                {
                    test: /\.(woff|woff2|eot|ttf|svg)$/i,
                    exclude: /node_modules/,
                    loader: 'url-loader'
                }
            ]
        },
        plugins: [
            new _conf.CleanWebpackPlugin(pathsToClean),
            // new CircularDependencyPlugin({
            //     // `onStart` is called before the cycle detection starts
            //     onStart({ compilation }) {
            //         console.log('start detecting webpack modules cycles');
            //     },
            //     // `onDetected` is called for each module that is cyclical
            //     onDetected({ module: webpackModuleRecord, paths, compilation }) {
            //         // `paths` will be an Array of the relative module paths that make up the cycle
            //         // `module` will be the module record generated by webpack that caused the cycle
            //         compilation.errors.push(new Error(paths.join(' -> ')))
            //     },
            //     // `onEnd` is called before the cycle detection ends
            //     onEnd({ compilation }) {
            //         console.log('end detecting webpack modules cycles');
            //     },
            // }),
            new _conf.webpack.HotModuleReplacementPlugin(),
            new _conf.MiniCssExtractPlugin({
                // Options similar to the same options in webpackOptions.output
                // both options are optional
                filename: "[name].[hash].css",
            }),
            new _conf.HtmlWebpackPlugin({
                inject: false,
                hash: true,
                template: _conf.frontEntryPoint.html,
                filename: 'index.html'
            }),
            new _conf.WebpackMd5Hash()
        ]
    };
};


